<?php

/**
 * This is the model base class for the table "error".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Error".
 *
 * Columns in table "error" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $code
 * @property string $ar_text
 * @property string $en_text
 * @property string $tr_text
 *
 */
abstract class BaseError extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'error';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Error|Errors', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code', 'length', 'max'=>45),
			array('ar_text, en_text, tr_text', 'safe'),
			array('code, ar_text, en_text, tr_text', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, ar_text, en_text, tr_text', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'ar_text' => Yii::t('app', 'Ar Text'),
			'en_text' => Yii::t('app', 'En Text'),
			'tr_text' => Yii::t('app', 'Tr Text'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('ar_text', $this->ar_text, true);
		$criteria->compare('en_text', $this->en_text, true);
		$criteria->compare('tr_text', $this->tr_text, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}